### ISSUE TITLE
Break up test utils into multiple tests

### ISSUE THREAD

**Issue by trigaten** [ALLAN-DIP/baseline_bots#131]
This entire file is a single test:

https://github.com/ALLAN-DIP/baseline_bots/blob/3ecc0efbed0de3f6ad63012de660e97e12b2c290/tests/utils_test.py#L1

**Comment by kartik2112** [comment]
I could split this. Do you suggest this to be having multiple files like these:
parse_fct_test.py
parse_prp_test.py
?

**Comment by trigaten** [comment]
> I could split this. Do you suggest this to be having multiple files like these: parse_fct_test.py parse_prp_test.py ?

Not necessarily; is this file just testing parses? If this is the case, instead of multiple files, you should do multiple tests.
