### ISSUE TITLE
Some docs not showing up

### ISSUE THREAD

**Issue by trigaten** [ALLAN-DIP/baseline_bots#142]
From this file: https://github.com/ALLAN-DIP/baseline_bots/blob/main/docs/source/development.rst
The following doesnt show up on the website:
```
If using VSCode, run `unset PROMPT_COMMAND` in the terminal or add it to .bashrc
Otherwise, you may see a lot of `__vsc_prompt_cmd_original`
```

**Comment by kkahadze** [comment]
@trigaten I believe we just need to change the link in the sidebar. If you look at the vercel sites generated at the [latest commit](https://github.com/ALLAN-DIP/baseline_bots/commit/6870ac1d717443d10b92b281a02ab8431b5f42b4), everything shows up.

These are the links:
[b-henna.vercel.app](https://b-henna.vercel.app/)
[baseline-bots-allan-dip.vercel.app](https://baseline-bots-allan-dip.vercel.app/)
[baseline-bots-git-main-allan-dip.vercel.app](https://baseline-bots-git-main-allan-dip.vercel.app/)

It seems that the sidebar instead points to [baseline-bots-git-updatedocs-allan-dip.vercel.app](https://baseline-bots-git-updatedocs-allan-dip.vercel.app/) which has old docs but I do not have permission to change it.

**Comment by trigaten** [comment]
@kkahadze I updated the link to https://baseline-bots-allan-dip.vercel.app/

Thanks for the investigative work :)
