### ISSUE TITLE
Attempt to remove gen_coroutine from realpolitik

### ISSUE THREAD

**Issue by trigaten** [ALLAN-DIP/baseline_bots#22]
https://github.com/ALLAN-DIP/baseline_bots/blob/ab8e2442e9e4f5984c4a557c4a651ecbbd2e8e5f/src/baseline_bots/bots/dipnet/RealPolitik.py#L51

It seems like this decorator shouldn't be needed.

**Comment by kartik2112** [comment]
Why is this needed?

**Comment by aphedges** [comment]
`RealPolitik` was removed in 2d14df3b98caab35308cddce5f7ea57812f76a8d, so this issue is moot.
