### ISSUE TITLE
Put how to deal with black permission error in documentation.

### ISSUE THREAD

**Issue by trigaten** [ALLAN-DIP/baseline_bots#43]
> black src/
> make: execvp: black: Permission denied
> make: *** [Makefile:2: format_code] Error 127

Try chmodding the makefile:

chmod 777 -R Makefile

Also I am working on integrating diplomacy_research into CI currently.

_Originally posted by @trigaten in https://github.com/ALLAN-DIP/baseline_bots/issues/42#issuecomment-1263594836_

**Comment by aphedges** [comment]
This appears to have been solved because Black now works in CI.
