### ISSUE TITLE
Convert Dipnet orders to DAIDE

### ISSUE THREAD

**Issue by trigaten** [ALLAN-DIP/baseline_bots#45]
See https://github.com/trigaten/DAIDE/issues/3

We need a function to be placed in `utils.py` that can do this.

**Comment by kartik2112** [comment]
Could someone help me out by letting me know if I am missing any types of orders and formats for possible dipnet order outputs wrt the following list?

* A PAR H --> (FRA AMY PAR) HLD
* A PAR - MAR --> (FRA AMY PAR) MTO MAR
* A PAR R MAR --> (FRA AMY PAR) MTO MAR
* A BUD S F TRI --> (AUS AMY BUD) SUP (AUS FLT TRI)
* A PAR S A MAR - BUR --> (FRA AMY PAR) SUP (FRA AMY MAR) MTO BUR
