### ISSUE TITLE
[refactor] Make bot API consistent

### ISSUE THREAD

**Issue by trigaten** [ALLAN-DIP/baseline_bots#53]
All bots should have a `__call__` method which takes in received messages, and perhaps optionally the current phase/season. It should return a dictionary which may contain orders, messages, or both.

Previously, we decided that our bots should have `gen_messages` and `gen_orders` functions. It is not necessary for all bots to have these functions, but they can be used as internal utilities.

**Comment by aphedges** [comment]
I have completed something similar to this over multiple PRs over the past couple of months. Although I did not follow the exact instruction, all bots now have a consistent interface through the `__call__()` method.
