### ISSUE TITLE
[SOA_bot] get_proposals check for valid proposals

### ISSUE THREAD

**Issue by trigaten** [ALLAN-DIP/baseline_bots#55]
`def get_proposals(self, rcvd_messages: List[Tuple[int, Message])` that currrently in SOA, shouldn't it be in utils.py ?
Plus, this function should check if proposals are valid
is it for bot's units?
are the moves valid? (cross check in game power possible moves)

-- @wwongkamjan

**Comment by kartik2112** [comment]
This function should now return set of valid_proposals and invalid_proposals. @wwongkamjan, I have added this function usage in soa_bot.py. I guess, we would also need to send REJ messages for the invalid_proposals back to the sender.

**Comment by kartik2112** [comment]
This would be related to #54
