### ISSUE TITLE
get_state_value add two more options to calculate state_value

### ISSUE THREAD

**Issue by wwongkamjan** [ALLAN-DIP/baseline_bots#61]
**From jbg**
rollout with "random moves" = sampling from the weighted ranked list of DipNet suggested moves

**From Jonathan Kummefeld**
one alternative value function is some combination of:
(a) Change in SCs
(b) How close the proposed orders are to what we would do anyway (closer is better)
(c)How many cross-power supports happen if you make the moves
Maybe 10(a) + (b) + 2(c) ? That means SCs dominate, and the others are tie-breakers, with move changes that lead to supports being worth changing for

**Comment by kartik2112** [comment]
This can be closed if it's completed. @wwongkamjan

**Comment by wwongkamjan** [comment]
yes it's done.
