### ISSUE TITLE
[Order randomization] Deal with ANDs

### ISSUE THREAD

**Issue by trigaten** [ALLAN-DIP/baseline_bots#66]
We would be dealing with these types of messages from other powers:
```
PRP (ORR (XDO ((RUS AMY WAR) MTO PRU)) (XDO ((RUS FLT SEV) MTO RUM)) (XDO ((RUS AMY PRU) MTO LVN)))

PRP(XDO((TUR FLT ANK) MTO BLA) AND XDO((RUS AMY SEV) MTO RUM) AND (XDO((ENG AMY LVP) HLD)))
``` 

- @kartik2112

**Comment by kartik2112** [comment]
I think this is done? @kkahadze

**Comment by kartik2112** [comment]
I believe this is already completed right?

**Comment by kkahadze** [comment]
@kartik2112 It only deals with correct DAIDE format currently, I am updating it now to deal with non-DAIDE such as:
_PRP(XDO((TUR FLT ANK) MTO BLA) AND XDO((RUS AMY SEV) MTO RUM) AND (XDO((ENG AMY LVP) HLD)))_

**Comment by kartik2112** [comment]
But if we use non-DAIDE messages we won’t be able to use DAIDE++ syntax checker on the input and output as suggested in the previous student meeting.

**Comment by aphedges** [comment]
We no longer allow invalid DAIDE, so this should not be implemented.
