### ISSUE TITLE
[SOA bot] DAIDE message received verification guard rail to prevent bot from crashing

### ISSUE THREAD

**Issue by kartik2112** [ALLAN-DIP/baseline_bots#72]
Could use DAIDE++ to verify the message received.

Caveat:
Doesn't work for messages such as `PRP( XDO() AND XDO())` which is expected from the eval but is incorrect DAIDE

**Comment by kartik2112** [comment]
As of now, if the message doesn't follow the structure defined in parser, the bot crashes instead of HUHing

**Comment by aphedges** [comment]
As of c5236bb443cafd5c97f92e42b2185a67eeb880ce, we now reject all incoming invalid DAIDE messages.
