### ISSUE TITLE
[soa_test_debugging] Fix game instance issue

### ISSUE THREAD

**Issue by wwongkamjan** [ALLAN-DIP/baseline_bots#83]
issue: run SOA_test.py will return an error 

`AttributeError: 'Jsonable' object has no attribute 'victory'`

due to `get_best_proposer(..., game)` in `utils.py `

The current logic is to copy a parent class of input of `game` --- we assume that game input is `NetworkGame` for TACC https. However, this will be an error when we input a `Game` instance. 

`Game` https://github.com/SHADE-AI/diplomacy/blob/master/diplomacy/engine/game.py
`NetworkGame` (`Game` as parent) https://github.com/SHADE-AI/diplomacy/blob/master/diplomacy/client/network_game.py

**Comment by trigaten** [comment]
Please specify the branch (is this currently an issue in main)?

**Comment by wwongkamjan** [comment]
branch: soa_test_debugging
